const ShopData = [
  {
    ID: 1,
    State: "Jammu and Kashmir",
    District: "Anantnag",
    Market: "Anantnag Vegetable Market",
    Name: "Apple",
    Type: "Fruit",
    Date: "2023-08-06",
    TodayPrice: 30,
    YesterdayPrice: 35,
    DayBeforeYesterdayPrice: 40,
    Quantity: 1,
    Image:
      "https://res.cloudinary.com/duycnul2b/image/upload/v1691160878/apple_hd4ugm.jpg",
  },
  {
    ID: 2,
    State: "Jammu and Kashmir",
    District: "Anantnag",
    Market: "Anantnag Vegetable Market",
    Name: "Banana",
    Type: "Fruit",
    Date: "2023-08-06",
    TodayPrice: 40,
    YesterdayPrice: 45,
    DayBeforeYesterdayPrice: 50,
    Quantity: 1,
    Image:
      "https://res.cloudinary.com/dipkglaib/image/upload/v1691778129/bananas-1-e1624909301641.jpg.optimal_1_dra9dc.jpg",
  },
  {
    ID: 3,
    State: "Jammu and Kashmir",
    District: "Anantnag",
    Market: "Anantnag Vegetable Market",
    Name: "Cabbage",
    Type: "Vegetable",
    Date: "2023-08-06",
    TodayPrice: 20,
    YesterdayPrice: 25,
    DayBeforeYesterdayPrice: 30,
    Quantity: 1,
    Image:
      "https://res.cloudinary.com/dipkglaib/image/upload/v1691780285/download_13_1_n3p0qn.jpg",
  },
  {
    ID: 4,
    State: "Jammu and Kashmir",
    District: "Anantnag",
    Market: "Anantnag Vegetable Market",
    Name: "Carrot",
    Type: "Vegetable",
    Date: "2023-08-06",
    TodayPrice: 25,
    YesterdayPrice: 30,
    DayBeforeYesterdayPrice: 35,
    Quantity: 1,
    Image:
      "https://res.cloudinary.com/dipkglaib/image/upload/v1691776861/download_1_1_fd4qv2.jpg",
  },
];
export default ShopData;
